### ISSUE TITLE
Note: Details is not supported in IE11

### ISSUE THREAD

**Issue by kevinpoot** [a11y-collective/demos#9]
https://github.com/a11y-collective/demos/blob/bcffa04888f61ae0f2c1cac31116b7463fb86dab/en/aria/accordion.html#L26

Just food for thought. IE11 does not support the `<detail> `and `<summary>` element. Even though this browser is outdated, it is still in use. I would mention this in the course and maybe show a way that works in all browsers.

**Comment by rianrietveld** [comment]
@kevinpoot 
It is an example of how easy it could be if all browsera and AT will support this, I address it in the coursee with a link to a workaround.  I will add IE11 to the text explicitly, thanks.
